from __future__ import annotations

import json
from pathlib import Path

from . import router as router_module
from .catalog_rows import (
    catalog_entry,
    chatgpt_passthrough_entries,
    chatgpt_passthrough_entry,
    shim_route_catalog_entry,
    with_provider_prefix,
)
from .settings import (
    PROVIDER_NAME,
    ShimModel,
    available_model_slugs,
    chatgpt_passthrough_available,
    default_model_slug,
)
from .cursor_passthrough import cursor_catalog_entry, cursor_passthrough_available


__all__ = [
    "catalog_entry",
    "chatgpt_passthrough_entries",
    "chatgpt_passthrough_entry",
    "codex_config_overrides",
    "write_catalog",
    "write_config",
]


def write_catalog(models: list[ShimModel], path: Path, router_config=None) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    entries: list[dict] = []
    if router_config is not None and router_module.router_is_active(router_config, available_model_slugs(models)):
        entries.append(
            shim_route_catalog_entry(
                router_module.router_catalog_entry(router_config),
                provider="auto",
                provider_display_name="Codex Shim Router",
                source="codex-shim",
            )
        )
    if chatgpt_passthrough_available():
        entries.extend(
            shim_route_catalog_entry(
                entry,
                provider="chatgpt",
                provider_display_name="ChatGPT/OpenAI",
                source="ChatGPT passthrough",
            )
            for entry in chatgpt_passthrough_entries()
        )
    if cursor_passthrough_available():
        entry = cursor_catalog_entry()
        entry["display_name"] = with_provider_prefix(str(entry.get("display_name") or "Composer 2.5"), "Cursor")
        entry["isDefault"] = not chatgpt_passthrough_available()
        entries.append(
            shim_route_catalog_entry(
                entry,
                provider="cursor",
                provider_display_name="Cursor",
                source="Cursor subscription",
            )
        )
    # Catalog generation can run from a normal shell while provider credentials
    # are only available to codex-shim.service through LoadCredentialEncrypted.
    # Keep configured routes visible in Desktop; request-time routing still
    # enforces credential availability and reports clear missing-key errors.
    entries.extend(catalog_entry(model) for model in models)
    payload = {"version": 1, "models": entries}
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    return path


def write_config(models: list[ShimModel], path: Path, catalog_path: Path, port: int) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        default_slug = default_model_slug(models)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc
    text = f'''# Generated by codex-shim. This file is opt-in and is not ~/.codex/config.toml.
model = "{_toml_escape(default_slug)}"
model_provider = "{PROVIDER_NAME}"
model_catalog_json = "{_toml_escape(str(catalog_path))}"

[model_providers.{PROVIDER_NAME}]
name = "Codex Shim"
base_url = "http://127.0.0.1:{port}/v1"
wire_api = "responses"
experimental_bearer_token = "dummy"
request_max_retries = 3
stream_max_retries = 3
stream_idle_timeout_ms = 600000
'''
    path.write_text(text)
    return path


def codex_config_overrides(catalog_path: Path, default_slug: str, port: int) -> list[str]:
    return [
        f'model="{_toml_escape(default_slug)}"',
        f'model_provider="{PROVIDER_NAME}"',
        f'model_catalog_json="{_toml_escape(str(catalog_path))}"',
        f'model_providers.{PROVIDER_NAME}.name="Codex Shim"',
        f'model_providers.{PROVIDER_NAME}.base_url="http://127.0.0.1:{port}/v1"',
        f'model_providers.{PROVIDER_NAME}.wire_api="responses"',
        f'model_providers.{PROVIDER_NAME}.experimental_bearer_token="dummy"',
        f'model_providers.{PROVIDER_NAME}.request_max_retries=3',
        f'model_providers.{PROVIDER_NAME}.stream_max_retries=3',
        f'model_providers.{PROVIDER_NAME}.stream_idle_timeout_ms=600000',
    ]


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
